
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
data:
  configuration-file: |
    server.port: {{ .Values.containerPort }}
    server.log-level: {{ .Values.logLevel }}

    tools.weather:
      host: "tool-openweathermap"
      port: 5555
